server:
  port: 8080

spring:
  profiles:
    active: local
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database-geo-changelog.xml

  datasource:
    url: jdbc:postgresql://postgres:5432/skillbox
    username: geo
    password: geo
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: geo
    open-in-view: false
