apiVersion: v1
kind: Secret
metadata:
  name: microservice-geo
stringData:
  DB_USERNAME: geo
  DB_PASSWORD: geo
  DB_HOST: postgres-service
  DB_SCHEMA: geo
  DB_DATABASE: skillbox
  REDIS_PASS: skillbox